[sssd]
config_file_version = 2
domains = tunnel.lab
services = nss, pam

[domain/tunnel.lab]
id_provider = ad
access_provider = permit
ad_domain = tunnel.lab
krb5_realm = TUNNEL.LAB
use_fully_qualified_names = False
fallback_homedir = /home/%u
default_shell = /bin/bash
ldap_id_mapping = True
dyndns_update = False
enumerate = False
